### ISSUE TITLE
Issue related pfSense Captive Portal/SMS sending.

### ISSUE THREAD

**Issue by aro28** [pertoft/pfSense-Custom-Captive-Portal-SMS#1]
Dear Ptertoft,
Fist of all i want to thank you for sharing of this useful project.

I want to adapt it to my country.
I installed and configured everything as mention on Readme file.
I installed playSMS with Kannel in Ubuntu Server as well. 
At this moment Captive Portal page is working(authorization page), but sms is not sending.

Could you please advise how to change SMSC and SMPP configuration settings into the portal-smscode.php file? 

Sending sms from url is working now.
Thank you advance!

Best,
Ruslan

**Comment by pertoft** [comment]
Hi Ruslan,

Thanks for giving my code a shot. There are some room for improvements :-)

The SMS based captive application has been use for an event, an i have not had the time to make everything "nice and smooth". 

However, you can look in portal-smscode.php (https://github.com/pertoft/pfSense-Custom-Captive-Portal-SMS/blob/master/portal-smscode.php) line 151 and on.

`function sendSMS($to,$message)
{
//SMSC Configuration
$server = "127.0.0.1";
$port = 2775;
$system_id = 1;
$system_type = 1;
$login= "xxx";
$pass = "yyy";
$to_ok = "";
$from="1234";
`

The current deployment use the SMPP SMS protocol, but it can be anything. I have included the SMPP class in the bottom of the file. If you need to use another SMS provider, e.g. Form POST based SMS, you can update the `function sendSMS($to,$message)` to use what ever service.

In my case the SMPP magic, are defined on line 205 and on.

`try
{
#require_once "smpp.php";
$tx=new SMPP($server,$port);
#$tx->debug=true;
$tx->system_type=$system_type;
$tx->addr_npi=1;
#print "### open status: ".$tx->state."\n";
$tx->bindTransmitter($system_id,$login);
$tx->sms_source_addr_npi=1;
$tx->sms_source_addr_ton=1;
$tx->sms_dest_addr_ton=1;
$tx->sms_dest_addr_npi=1;
#Send as FLASH SMS
#$tx->$sms_data_coding=240;
$ret = $tx->sendSMS($from,$to_ok,$message);
$tx->close();
unset($tx);
} catch (ErrorException $e) {
	print "ERROR: $e";
}`

Feel free to ask any further questions :-)

Best regards,
Per

**Comment by aro28** [comment]
Hi ,
I've a little experience in PHP.  Could you please advise what fields of PHP code i should change?
I installed PlaySMS and gammu. Currently i can send messages via PlaySMS web interface only.

Can you described in more detail. As i understand in portal-smscode.php line 151 i should type my GAMMU server address, login and password. Is it right? And what about $port = 2775 number? What should i type here?

function sendSMS($to,$message)
{
//SMSC Configuration
$server = "127.0.0.1";
$port = 2775;
$system_id = 1;
$system_type = 1;
$login= "xxx";
$pass = "yyy";
$to_ok = "";
$from="1234";

Thank you advance!
Ruslan

**Comment by pertoft** [comment]
Hi Ruslan,

I dont know playsms, but according to the following article: https://aacable.wordpress.com/2015/07/30/playsms-send-sms-via-scriptcli-using-webservices-token/

I could imagine somthing like (untested):

```
function sendSMS($to,$message)
{
// playSMS username/account for sending SMS
$username = 'admin';
 
// Webservices token for above username
$token = '1194df9e20d06c3790f0c6fef49f174a';
 
// playSMS Webservices URL
$playsms_ws = 'http://localhost/playsms/index.php?app=ws';
 
    $ws = $playsms_ws . '&u=' . $username . '&h=' . $token . '&op=pv';
    $ws .= '&to=' . urlencode($to) . '&msg='.urlencode($message) . '&nofooter=1';
    $ret = @file_get_contents($ws);
 
    echo "OK: message sent" . PHP_EOL;
} else {
    echo "ERROR: message is empty" . PHP_EOL;
}

```

**Comment by aro28** [comment]
Hi Per,
Thank you for spending the time to discuss my issue.
Am I correctly understand that I can solve a sending of SMS issue without PlaySMS and Gammu gateway? I can just use SMPP SMS protocol into PHP code and no need to install(playsms and gammu) to separate server. As i understand for using of SMPP SMS protocol you had registered to external SMPP server and they provided login and password to you?

---------------------------------------------------------
Ok. If i want to use my own SMS gateway i have to change my county code in 175 line  and in  line 151 of "portal-smscode.php" file. Is it right?
---------------------------------------------------------
HERE:
function sendSMS($to,$message) { //SMSC Configuration $server = "127.0.0.1"; $port = 2775; $system_id = 1; $system_type = 1; $login= "xxx"; $pass = "yyy"; $to_ok = ""; $from="1234";


AND HERE:

//Match number 12345678
if(preg_match("/^(\d{8})$/", trim($to), $matches))
{
                $to_ok = "+45".$matches[1];
}

**Comment by pertoft** [comment]
It is a regular expressions, which verify that the user has entered eight digits (no letters etc). E.g. 
12345678 = OK
123456789 = FAIL
1234567A = FAIL

Then I append the danish Country code to the 8 digits, as i will only allow danish texts.
E.g. 
+4512345678

**Comment by aro28** [comment]
yes, understand about country code digits.

Bus it doesn't work for me since i can't configure this PHP code for my SMSC(Gammu) gateway for 
As i understand for your deployment you was used external SMPP server or SMSC gateway. Is it correct?

Any adea or suggestions?

**Comment by pertoft** [comment]
Yes, it is correct. The code supports an external SMSC gateway using the SMPP protocol.
As i wrote in the comment above, you can use any SMSC or service to push an text. Just include your API code in the sendSMS() function.

**Comment by aro28** [comment]
-----------------------------
Hi,
Currently. i installed Kannel Gateway which supports SMPP protocol as well.

Also, i'm able to send from Kannel gateway by url:
http://172.20.20.11:13013/cgi-bin/sendsms?username=kannel&password=kannel&to=MyMobileNumber&text=HeyMan+SMSserver+WORKS

I don't know why but from below PHP code it cannot generate and send messages to my mobile.
Maybe you can find what's wrong with my code and me :) 
Could you please check my  attached "portal-smscode.txt" file
.
-----------------------------------

[portal-smscode.txt](https://github.com/pertoft/pfSense-Custom-Captive-Portal-SMS/files/752078/portal-smscode.txt)

**Comment by aro28** [comment]
My county code +996 (XXX) (XXXXXX)
+996 + 9 digits
