### ISSUE TITLE
no authentication

### ISSUE THREAD

**Issue by zigldotnet** [pertoft/pfSense-Custom-Captive-Portal-SMS#2]
Thank you for a wonderful project.
I changed the settings for your SMS provider. SMS was successfully sent.
But after the page is updated, once again I get on the phone number entry form. What settings should be on page Captive Portal? As a database table radcheck consistent with the authentication of pfsens?
I would be grateful for a detailed example pfsense settings. Pfsense 2.3.2.
Sorry for my bad English.

**Comment by aro28** [comment]
Hi Zigldotnet,
You mean when you entered your mobile number on PfSence Captive Portal page you was able to receive sms with code?
Best,

**Comment by zigldotnet** [comment]
Hi.
Yes, I get the code. I enter it in the verification field. After ten seconds, the page refreshes and I again on the page entering the phone number.

**Comment by pertoft** [comment]
Hi,

It seems like your portal-validate.php isnt working properly. I could imagine problems with the MySQL connection.

You can try to debug by inserting the php colde
<?PHP
var_dump($_POST);
var_dump($_SESSION);
?>

This will dump the current session and post variables. 
You can post them and I can have a look at it.

Thanks
Per

**Comment by aro28** [comment]
Hi Zigldotnet,
Will be very appreciated if you could send me your PHP code(portal-smscode.php) to my email. 
I want to see your solutinon as well.
prostotak1981@gmail.com
Thank you!

**Comment by zigldotnet** [comment]
thanks for the help. I've already decided their problems. I took only a code to send SMS, and the rest from the other project. enough for me
