### ISSUE TITLE
Problem with mySQL

### ISSUE THREAD

**Issue by YANTARik** [pertoft/pfSense-Custom-Captive-Portal-SMS#3]
Good day. I tried to use your code to solve the problem with access to the public network.
at the last stage, after entering the password from sms, I get the error:
Fatal error: Call to undefined function mysql_connect () in /usr/local/captiveportal/portal-validate.php on line 97 Call Stack: 0.0001 232400 1. {main} () /usr/local/captiveportal/portal-validate.php : 0 PHP ERROR: Type: 1, File: /usr/local/captiveportal/portal-validate.php, Line: 97, Message: Call to undefined function mysql_connect ()

**Comment by YANTARik** [comment]
I beg your pardon. My mistake. Configuring PHP.ini solved the problem

**Comment by YANTARik** [comment]
Dear pertoft. I'm trying to figure it out with Pfsense VS CP, to test your instance of the portal with a password via SMS, the last step is missing - sql database. could you show how organized they are with you?

**Comment by pertoft** [comment]
Hello,

I have not used the application for some time, but i recall you need to to install mysql server on pfsense or on another host.

Here are some examples of how pkg_add works - i dont know if it works on the later versions of pfsense:
http://www.netpower.fr/sites/default/files/soft/html-doc/pfSense-cp-auth-onestep_0.html
